#!/bin/bash -x
# fullRSS takes the url's piped in and extract titles and links
# takes each line in en.rss and downloads to en.xml
# then creates en.link and en.title
# paste to en.match if en.link and en.title match
# if not match then save to en.error for fixing later

fullRSS() {
        while read LINE; do
                wget "$LINE" -O - >tmp.xml
                sed -e 's/<!\[CDATA\[//g; s/\]\]>//g' tmp.xml | grep '<link>' >tmp.link
                sed -e 's/<!\[CDATA\[//g; s/\]\]>//g' tmp.xml | grep '<title>' >tmp.title
                if [ "$(wc -l < tmp.link)" -eq "$(wc -l < tmp.title)" ]; then
                        paste tmp.link tmp.title >>tmp.match
                else
                        echo 'Warning: No Match!' >>tmp.error;
                fi
        done < <(cat "$@")
}
fullRSS
