#!/bin/bash -x
# getRSS takes a list of urls, download and extract links and titles (in fullRSS), and post newer items (in postRSS)
# ex: getRSS en (en.rss)
# takes each line in en.rss and downloads to en.xml

getRSS() {
        file=$1
        # getRSS() takes a parameter to decide which RSS file to use (en or vi)
        mv /home4/yisvfxmy/public_html/giavi/$file.new /home4/yisvfxmy/public_html/giavi/$file.old
        echo "Passing to fullRSS " $file
        cat /home4/yisvfxmy/public_html/giavi/$file.rss |/home4/yisvfxmy/public_html/giavi/fullRSS
        /home4/yisvfxmy/public_html/giavi/postRSS $file
}
rm tmp.*
getRSS $1
